<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Komunitas_model extends CI_Model
{

    public $table = 'komunitas';
    public $id = 'id_komunitas';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }


    // datatables
    function json() {

        $this->datatables->select('id_komunitas,judul_komunitas,isi_komunitas,url_komunitas,id_kategori,status_komunitas,tanggal,waktu');
        $this->datatables->from('komunitas');
        //add this line for join
        //$this->datatables->join('table2', 'komunitas.field = table2.field');
        $baseurl = base_url();
        $this->datatables->add_column('gambar_komunitas', "<center><img src='$baseurl/assets/images/produk/$1' width='80px'></center>", 'gambar_komunitas');

        $this->datatables->add_column('action', anchor(site_url('adminweb/komunitas/read/$1'),'Read')." | ".anchor(site_url('adminweb/komunitas/update/$1'),'Update')." | ".anchor(site_url('adminweb/komunitas/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_komunitas');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_komunitas', $q);
	$this->db->or_like('judul_komunitas', $q);
	$this->db->or_like('gambar_komunitas', $q);
	$this->db->or_like('isi_komunitas', $q);
	$this->db->or_like('url_komunitas', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('status_komunitas', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('waktu', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_komunitas', $q);
	$this->db->or_like('judul_komunitas', $q);
	$this->db->or_like('gambar_komunitas', $q);
	$this->db->or_like('isi_komunitas', $q);
	$this->db->or_like('url_komunitas', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('status_komunitas', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->or_like('waktu', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Komunitas_model.php */
/* Location: ./application/models/Komunitas_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-30 12:32:52 */
/* http://harviacode.com */